/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 16 20:40:43 GMT 2023
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import org.apache.commons.lang3.text.translate.CharSequenceTranslator;
import org.apache.commons.lang3.text.translate.LookupTranslator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.testcarver.testcase.EvoSuiteXStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LookupTranslator_ESTest extends LookupTranslator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][7];
      CharSequence[] charSequenceArray1 = new CharSequence[9];
      charSequenceArray1[0] = (CharSequence) "<string-buffer>one</string-buffer>";
      charSequenceArray1[1] = (CharSequence) "<string-buffer>one</string-buffer>";
      charSequenceArray1[2] = (CharSequence) "<string-buffer>one</string-buffer>";
      charSequenceArray1[3] = (CharSequence) "<string-buffer>one</string-buffer>";
      charSequenceArray1[4] = (CharSequence) "<string-buffer>one</string-buffer>";
      charSequenceArray1[5] = (CharSequence) "<string-buffer>one</string-buffer>";
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      charSequenceArray1[6] = (CharSequence) stringBuffer0;
      charSequenceArray1[7] = (CharSequence) "<string-buffer>one</string-buffer>";
      charSequenceArray1[8] = (CharSequence) "<string-buffer>one</string-buffer>";
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      lookupTranslator0.translate(charSequenceArray1[4]);
      LookupTranslator lookupTranslator1 = new LookupTranslator(charSequenceArray0);
      assertFalse(lookupTranslator1.equals((Object)lookupTranslator0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[0][3];
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      CharSequenceTranslator.hex(1964);
      int int0 = lookupTranslator0.translate((CharSequence) "7AC", 1964, (Writer) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object object0 = EvoSuiteXStream.fromString("<string-buffer>one</string-buffer>");
      CharSequence[] charSequenceArray0 = new CharSequence[2];
      charSequenceArray0[0] = (CharSequence) object0;
      charSequenceArray0[1] = (CharSequence) object0;
      CharSequence[][] charSequenceArray1 = new CharSequence[2][9];
      charSequenceArray1[0] = charSequenceArray0;
      charSequenceArray1[1] = charSequenceArray0;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LookupTranslator lookupTranslator0 = new LookupTranslator((CharSequence[][]) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Object object0 = EvoSuiteXStream.fromString("<string-buffer>one</string-buffer>");
      Object object1 = EvoSuiteXStream.fromString("<string-buffer>one</string-buffer>");
      CharSequence[] charSequenceArray0 = new CharSequence[2];
      charSequenceArray0[0] = (CharSequence) object0;
      charSequenceArray0[1] = (CharSequence) object1;
      CharSequence[][] charSequenceArray1 = new CharSequence[1][8];
      charSequenceArray1[0] = charSequenceArray0;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray1);
      String string0 = lookupTranslator0.translate(charSequenceArray0[0]);
      assertEquals("one", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[0][7];
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      CharSequenceTranslator.hex((-3357));
      lookupTranslator0.translate((CharSequence) "FFFFF2E3");
      LookupTranslator lookupTranslator1 = new LookupTranslator(charSequenceArray0);
      assertFalse(lookupTranslator1.equals((Object)lookupTranslator0));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Object object0 = EvoSuiteXStream.fromString("<string-buffer>one</string-buffer>");
      CharSequence[] charSequenceArray0 = new CharSequence[2];
      charSequenceArray0[0] = (CharSequence) object0;
      CharSequence[][] charSequenceArray1 = new CharSequence[1][3];
      charSequenceArray1[0] = charSequenceArray0;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray1);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[9][8];
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }
}
